baseurl = "https://konfound-project.github.io"
DefaultContentLanguage = "en"
title = "KonFound-It!"
theme = "beautifulhugo"
publishDir = "docs"

googleAnalytics = "G-P0EMSX02Q0"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"



[Params]
  homeTitle = "KonFound-It!" # Set a different text for the header on the home page
  subtitle = "Quantify the Robustness of Causal Inferences"
  mainSections = [] # Define a page to show up below landing page (e.g., "post", "posts")
  logo = "img/konfound-logo.png" # Expecting square dimensions
  favicon = "img/konfound-logo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."


#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"



[Author]
#  Customize social icons in >> themes >> beautifulhugo >> data >> beautifulhugo >> social.toml
#  Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#  name = "Some Person"
  website = "konfound-it.org"
  group = "konfound-it"
#  email = "youremail@domain.com"
  github = "konfound-project"
  r-package = "konfound"
  stata-package = "1536867X19874223"
  r-shiny = "konfound-it"
  benchmark = "benchmark"
#  facebook = "username"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  medium = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"



[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "tools"
    name = "Tools"
    weight = 2

[[menu.main]]
    parent = "tools"
    name = "Shiny App"
    url = "https://konfound-project.shinyapps.io/konfound-it/"
    weight = 1

[[menu.main]]
    parent = "tools"
    name = "Benchmarks"
    url = "https://konfound-project.shinyapps.io/wwc-sensitivity-benchmark/"
    weight = 1

[[menu.main]]
    parent = "tools"
    name = "R Package"
    url = "https://konfound-project.github.io/konfound/"
    weight = 2

[[menu.main]]
    parent = "tools"
    name = "R Paper"
    url = "https://doi.org/10.21105/joss.05779"
    weight = 3

[[menu.main]]
    parent = "tools"
    name = "Stata Paper"
    url = "https://doi.org/10.1177/1536867X19874223"
    weight = 4

[[menu.main]]
    identifier = "support"
    name = "Support"
    weight = 3

[[menu.main]]
    parent = "support"
    name = "FAQ"
    url = "page/faq"
    weight = 1

[[menu.main]]
    parent = "support"
    name = "Resource Overview"
    url = "page/resources"
    weight = 2

[[menu.main]]
    parent = "support"
    name = "Publications"
    url = "page/publications"
    weight = 3

[[menu.main]]
    parent = "support"
    name = "Talks"
    url = "page/talks"
    weight = 4

[[menu.main]]
    parent = "support"
    name = "Workshops"
    url = "page/workshops"
    weight = 5

[[menu.main]]
    parent = "support"
    name = "User Guide"
    url = "page/guide"
    weight = 6

[[menu.main]]
    parent = "support"
    name = "Forum"
    url = "https://groups.google.com/g/konfound-it"
    weight = 7

[[menu.main]]
    name = "News"
    url = "news/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 5



#[languages]
#  [languages.en]
#    contentDir = "content/en" # English
#  [languages.es]
#    contentDir = "content/es" # Spanish
#  [languages.zh-CN]
#    contentDir = "content/zh-CN" # Chinese
